# Generated by Django 3.0.6 on 2020-05-17 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realtor',
            name='top_seller',
            field=models.BooleanField(default=False),
        ),
    ]
